#!/usr/bin/env python3
"""
Embed the generated IME tables into a C source file so the wubi-ime binary is
self-contained (no external .tab needed at runtime - copy the one file anywhere).

Reads one or more `<symbol>=<path>` pairs and emits, to --out, a C file with a
byte array + length for each, plus a small accessor table:

    const unsigned char wubi_tab[]   = { ... };
    const unsigned long wubi_tab_len = ...;
    ... one per input ...

    const embedded_table embedded_tables[] = {
        { "wubi.tab",   IME_SCHEME_WUBI,   wubi_tab,   sizeof wubi_tab },
        { "pinyin.tab", IME_SCHEME_PINYIN, pinyin_tab, sizeof pinyin_tab },
    };
    const int embedded_tables_count = 2;

Usage:
    python3 gen_embed.py --out tables_embed.c \\
        wubi:wubi.tab:0 pinyin:pinyin.tab:1

Each argument is `symbol:path:scheme` (scheme 0=wubi 1=pinyin).
"""
import argparse
import os
import sys


def emit_array(f, symbol, data):
    f.write(f"static const unsigned char {symbol}[] = {{\n")
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        f.write("    " + ",".join(str(b) for b in chunk) + ",\n")
    f.write("};\n\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("specs", nargs="+", help="symbol:path:scheme triples")
    args = ap.parse_args()

    entries = []
    for spec in args.specs:
        parts = spec.split(":")
        if len(parts) != 3:
            sys.exit(f"bad spec '{spec}', expected symbol:path:scheme")
        symbol, path, scheme = parts[0], parts[1], int(parts[2])
        if not os.path.exists(path):
            sys.exit(f"table not found: {path} (run `make tables` first)")
        with open(path, "rb") as fh:
            data = fh.read()
        entries.append((symbol, os.path.basename(path), scheme, data))

    os.makedirs(os.path.dirname(os.path.abspath(args.out)) or ".", exist_ok=True)
    with open(args.out, "w") as f:
        f.write("/* Auto-generated by gen_embed.py - do not edit.\n")
        f.write(" * IME tables compiled into the binary (see load_tables()). */\n")
        f.write('#include "table.h"\n')
        f.write('#include "tables_embed.h"\n\n')
        for symbol, _base, _scheme, data in entries:
            emit_array(f, symbol, data)
        f.write("const embedded_table embedded_tables[] = {\n")
        for symbol, base, scheme, data in entries:
            f.write(f'    {{ "{base}", {scheme}, {symbol}, '
                    f"sizeof {symbol} }},\n")
        f.write("};\n")
        f.write(f"const int embedded_tables_count = {len(entries)};\n")

    total = sum(len(d) for _s, _b, _sc, d in entries)
    print(f"embedded {len(entries)} table(s), {total} bytes -> {args.out}")


if __name__ == "__main__":
    sys.exit(main())
